### ISSUE TITLE
InModuleScope gives error "Module 'MyModule' is not a Script module." in "Manifest"-type modules

### ISSUE THREAD

**Issue by mikeclayton** [pester/Pester#933]
Hi,

I've got a PowerShell *.psd1 Module which references some *.ps1 files in NestedModules and I'm trying to mock the functions defined in those *.ps1 files, but I'm having some problems. I've seen similar issues that recommend using InModuleScope, but when I do that I get the following error:

```
[-] Error occurred in Describe block 516ms
      RuntimeException: Module 'MyModule' is not a Script module.  Detected modules of the following types: 'Manifest'
      at Get-ScriptModule, C:\src\MyProject\packages\Pester\4.0.8\Functions\InModuleScope.ps1: line 128
```

I'll post my module's code in a follow-up comment, but I think the problem is because Get-ScriptModule (in Functions\InModuleScope.ps1) is filtering on modules that are of type "Script" (i.e. *.psm1) files, but I've got *.ps1 files referenced in a *.psd1 "Manifest" module.

```
$scriptModules = @($modules | & $SafeCommands['Where-Object'] { $_.ModuleType -eq 'Script' })
```

I can **seem** to fix the issue by adding "Manifest" module types to the check, as follows:

```
$scriptModules = @($modules | & $SafeCommands['Where-Object'] { $_.ModuleType -in @( 'Script', 'Manifest' ) } )
```

I don't really understand the whole Pester codebase well enough to know whether this might break any other scenarios, but I'll happily send a Pull Request if this looks like a valid fix.

Cheers,

Mike

**Comment by mikeclayton** [comment]
Code to reproduce issue:

**MyModule.psd1**
```
@{
ModuleVersion     = '1.0'
NestedModules     = @( "Invoke-PrivateMethod.ps1", "Invoke-PublicMethod.ps1" )
FunctionsToExport = @( "Invoke-PublicMethod" )
}
```

**Invoke-PrivateMethod.ps1**
```
function Invoke-PrivateMethod
{
    write-host "private method called!";
}
```

**Invoke-PublicMethod.ps1**
```
function Invoke-PublicMethod
{
    Invoke-PrivateMethod;
}
````

**Invoke-PublicMethod.Tests.ps1**
```
$ErrorActionPrefernce = "Stop";
Set-StrictMode -Version Latest;

Describe "Invoke-PublicMethod" {

    InModuleScope "MyModule" {

        Mock -CommandName "Invoke-PrivateMethod" `
             -MockWith    { write-host "private mock called!" };

        It "Should mock the private method" {
            Invoke-PublicMethod;
            Assert-MockCalled -CommandName "Invoke-PrivateMethod";
        }

    }

}
```

**Comment by alx9r** [comment]
For a module to be a `Script` [`ModuleType`](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.moduletype?redirectedfrom=MSDN&view=powershellsdk-1.1.0) you need to specify a `.psm1` file in the `RootModule` field of the manifest.  (FWIW, I didn't know this until just now.)  It looks like [this page](https://msdn.microsoft.com/en-us/library/dd878337(v=vs.85).aspx) is some authoritative documentation on the matter.  That page includes the following statement:

>Possible types for the root module can be empty (which will make this a Manifest module), the name of a script module (.psm1, which makes this a Script module), or the name of a binary module (.exe or .dll, which makes this a Binary module). Placing the name of a module manifest (.psd1) or a script file (.ps1) in this element will cause an error to occur.

Creating empty file `MyModule.psm1` and adding `RootModule = 'MyModule.psm1'` to the hashtable in `MyModule.psd1` and running again results in the following:

![image](https://user-images.githubusercontent.com/11237922/32621291-30d7e476-c534-11e7-840c-fa2d13b7ebf6.png)

**Comment by mikeclayton** [comment]
@axl9r - Nice find with the link to the documentation - it makes total sense, and the workaround looks like it'll be fine for my scenario.

I've also submitted a pull request which adds support for Manifest-type modules in case it's something you want to incorporate. I've included some additional tests in InModuleScope.Tests.ps1 to cover it as well.

Cheers,

Mike

**Comment by it-praktyk** [comment]
Fixed by #945

**Comment by craig-martin** [comment]
I've noticed the same error when NestedModules contains .psm1 files.  Changing the NestedModules items to .ps1 files resolves it.

**Comment by nohwnd** [comment]
@craig-martin do you have a simple repro? Please start a new issue.

**Comment by raandree** [comment]
Same here. I needed to add [that dummy psm1 file](https://github.com/raandree/JeaDsc/blob/feature/Sampler/source/JeaDsc.psm1) and reference it as RootModule in the module's psd1 file to make InModuleScope working.

**Comment by raandree** [comment]
Still facing this issue. @nohwnd, can you have a quick look at this, please?

**Comment by nohwnd** [comment]
@raandree on which Pester version are you?

**Comment by raandree** [comment]
It is 4.10.1. Is this fixed in 5?

**Comment by nohwnd** [comment]
I don't think this is fixed in any Pester version.
